sudo: required
services:
  - docker

before_install:
  - docker build -t testreact -f Dockerfile.dev . 

script:
  - docker run testreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-new"
  env: "DockerReactNew-env"
  bucket_name: "elasticbeanstalk-us-east-1-787614641643"
  bucket_path: "docker-react-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
